### ISSUE TITLE
zalgo

### ISSUE THREAD

**Issue by ArtskydJ** [TehShrike/read-write-lock#3]
In a real-world situation, it's hard to know if a callback will be called synchronously or asynchronously.

```js
var createMutex = require('./')
var mutex = createMutex()

emitter.on('event', function () {
  console.log('before')
  mutex.writeLock(function (release) {
    console.log('    inside')
    setTimeout(release, 100)
  })
  console.log('after')
})
```
Maybe this:
```
before
    inside
after
```
or maybe this:
```
before
after
    inside
```

**Comment by TehShrike** [comment]
You're right, I broke that just tonight when I switched to using async-each in https://github.com/TehShrike/read-write-lock/commit/c524c950355c344ce3d9946367a207e9cad00082

This line should be run in `process.nextTick`: https://github.com/TehShrike/read-write-lock/blob/master/index.js#L12

I'll change that quick for the next release.
